version: '3.7'
services:
  db:
    image: postgres:10.16
    ports:
      - "5432:5432"
    volumes:
      - ./pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=bc
      - POSTGRES_USER=bc
  bc-roles:
    image: bc-roles:0.0.1
    build:
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - 'BC_ROLE_MAPPING={"001 - Admin":"BC_ADMIN","002 - Clinical personnel":"BC_CLINICAL","003 - Warehouse personnel": "BC_WAREHOUSE" }'
      - DBHOST=db
      - 'DBPORT=5432'
      - DBUSER=bc
      - DB=bc
      - DBPASSWORD=${PG_PASSWORD}
